#!/usr/bin/env bash

NAME_DEVKIT="devkit"

DEVKIT_REF_ID_SYSD=sysd
DEVKIT_REF_ID_SSHD=sshd
DEVKIT_REF_ID_VPND=vpnd
DEVKIT_REF_ID_BOX=box
DEVKIT_REF_ID_BIN=bin

DEVKIT_REF_PREFIX="evo/${NAME_DEVKIT}"
DEVKIT_REF_SYSD=${DEVKIT_REF_PREFIX}:${DEVKIT_REF_ID_SYSD}
DEVKIT_REF_SSHD=${DEVKIT_REF_PREFIX}:${DEVKIT_REF_ID_SSHD}
DEVKIT_REF_VPND=${DEVKIT_REF_PREFIX}:${DEVKIT_REF_ID_VPND}
DEVKIT_REF_BOX=${DEVKIT_REF_PREFIX}:${DEVKIT_REF_ID_BOX}
DEVKIT_REF_BIN=${DEVKIT_REF_PREFIX}:${DEVKIT_REF_ID_BIN}

PARENT_COMMAND=$(ps -o comm= $PPID)

PATH_REPO_HOME=$( cd "${BASH_SOURCE[0]%/*}" && pwd )
PATH_LIB_HOME=$(realpath "$PATH_REPO_HOME/lib")
PATH_CONF_HOME=$(realpath "$PATH_REPO_HOME/conf")
PATH_TOOLBELT_HOME=$(realpath "$PATH_REPO_HOME/toolbelt")
PATH_IMAGES_HOME=$(realpath "$PATH_REPO_HOME/images")