version: '3.4'

# https://github.com/defn/docker-systemd

services:

  devkit_example_script:
    image: evo/devkit:bin
    container_name: devkit_example_script
    restart: unless-stopped
    ports:
      - "2222:22"           # needed for ssh (should match ansible-playbook setting)
    volumes:
      - ./src/hello-world.sh:/home/pi/hello-world.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # needed for systemd
    security_opt:
      - seccomp:unconfined  # needed for systemd
    tmpfs:
      - /run                # needed for systemd
      - /run/lock           # needed for systemd